spring:
  freemarker:
    suffix: .ftl
  mail:
    host: "smtp.gmail.com"
    port: 25
    username: "musicforall07@gmail.com"
    password: "PolyInkExt"
    properties:
      mail:
        transport:
          protocol: "smtp"
        smtp:
          auth: true
          starttls:
            enable: "true"
        debug: "true"
  data:
    mongodb:
      database: mailDispatcher
  http:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

server:
  port: 8090
app:
  attachmentsDirectory: "src/main/resources/temporary/"
